name: Android SDK PR checks

on:
  pull_request:
    paths-ignore:
      - '.github'

jobs:
  Check:
    uses: rees46/workflow/.github/workflows/reusable-android-checks.yaml@master
    permissions: write-all
    with:
      PROPERTIES_FILE: gradle.properties
      SIGNING_SECRET_KEY_RING_FILE: com.rees46.key.gpg
      SIGNING_SECRET_KEY_RING_FILE_LOCATION: ./personalizatio-sdk
      GOOGLE_SERVICES_FILE_LOCATION: ./sample
      GOOGLE_SERVICES_FILE_NAME: google-services.json
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_REES46: ${{ secrets.SONATYPE_REES46 }}
      SONATYPE_PERSONACLICK: ${{ secrets.SONATYPE_PERSONACLICK }}
      SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}
      GOOGLE_SERVICES_FILE_AS_BASE64_STRING: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64_STRING }}
