name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Repo sync"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    uses: rees46/workflow/.github/workflows/reusable-android-synchronization.yaml@refactor/android-sync
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
    with:
      targetRepository: personaclick/android-sdk
